name: Publish Docker image for unrar main

on:
  workflow_dispatch:
  push:
    branches:
      - "linuxserver/docker-unrar/main"

jobs:
  build-and-push-image:
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    uses: ./.github/workflows/build.yaml
    with:
      branch: docker-unrar/main
      image_name: ${{ github.repository }}/unrar
      image_tag: riscv64-latest
