name: Publish Docker image for sabnzbd master

on:
  workflow_dispatch:
  push:
    branches:
      - "linuxserver/docker-sabnzbd/master"

jobs:
  build-and-push-image:
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    uses: ./.github/workflows/build.yaml
    with:
      branch: docker-sabnzbd/master
      image_name: ${{ github.repository }}/unrar
      image_tag: latest
